# Generated by Django 4.1.7 on 2023-02-26 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bsae", "0003_remove_video_language_topic_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="topic",
            name="material",
            field=models.FileField(blank=True, null=True, upload_to="materials"),
        ),
    ]
